server:
  port: 8080

spring:
  application:
    name: guestbook
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/guestbook
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  servlet:
    multipart:
      enabled: true
      location: C:\\upload
      max-request-size: 30MB
      max-file-size: 10MB
#  sql:
#    init:
#      mode: always # 또는 embedded (내장 DB만)
  thymeleaf:
    cache: false #로컬 개발용

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.january.guestbook.domain
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: null

logging:
  level:
    org:
      springframework:
        security:
          web: trace
    com:
      january: debug
